### ISSUE TITLE
Kan ej logga in som admin

### ISSUE THREAD

**Issue by rn222cx** [mp222sf/1dv450-clientapplication#1]
Jag kunde inte logga in som admin på API:et med de uppgifter som finns i readme filen. Det gick dock att registrera en ny användare och generera en nyckel med, dock så fick jag ett meddelande som säger att det krävs minst 5 tecken för lösenord fast det krävdes minst 6

**Comment by mp222sf** [comment]
Fel av mig. Glömde ladda upp nya versionen av API:et. Har gjort det nu. Testa gärna clona ner API:et igen.
