### ISSUE TITLE
Cross-Origin Resource Sharing

### ISSUE THREAD

**Issue by rn222cx** [mp222sf/1dv450-clientapplication#2]
Fick inte tillgång till API:et p.g.a  Cross-Origin Resource Sharing (CORS)

Jag installerade rack-cors på API sidan och det fungerade igen

länk till rack-cors https://github.com/cyu/rack-cors

**Comment by mp222sf** [comment]
Fel av mig. Glömde ladda upp nya versionen av API:et. Har gjort det nu. Testa gärna klona ner API:et igen.

(Rack-cors finns redan på nya versionen som jag glömde ladda upp :+1: )
