### ISSUE TITLE
Kartan fungerar inte

### ISSUE THREAD

**Issue by rn222cx** [mp222sf/1dv450-clientapplication#3]
Det första jag stöter på är en karta som inte fungerar (se skärm dump nedan)

![image](https://cloud.githubusercontent.com/assets/8653353/13893647/ab8548b0-ed60-11e5-8a37-576c063047d5.png)

Problemet ligger i denna raden https://github.com/rn222cx/1dv450-clientapplication/blob/master/services/PizzaKartaService.js#L85

Värdena som pushas till markersList finns inte i objektet som hämtas från API:et.

**Comment by mp222sf** [comment]
Fel av mig. Glömde ladda upp nya versionen av API:et. Har gjort det nu. Testa gärna klona ner API:et igen.

(Bör fungera med nya API:et)

**Comment by rn222cx** [comment]
Det va lite synd för jag la ner mycket tid på att försöka få saker och ting att fungera igår. Men nu fungera det efter uppdateringen :+1:
