### ISSUE TITLE
Autensiering

### ISSUE THREAD

**Issue by rn222cx** [mp222sf/1dv450-clientapplication#6]
Tanken med laborationen är att nya resursägare ska kunna skapa/ändra och ta bort egna resurser.
Nu finns det bara en hårdkodad admin som kan utföra denna tjänsten.

I projektet skickas username och password med överallt, det hade varit smidigare att spara det i en kaka eller dylikt

En utloggnings funktion kan vara bra och implementera.

**Comment by mp222sf** [comment]
Har ändrat Autentiseringen. 
Nu sker följande.
-Användaren försöker logga in med rätt inloggningsuppgifter.
-Uppgifterna skickas till API-server.
-Uppgifterna kontrolleras och om de är korrekta så skickas ett token tillbaka till klienten.
-Detta token:et sparas på klienten i en kaka och används för att göra poster mot API:et. (skickas med vid POST/DELETE/PUT).
-(Token:et kontrolleras hela tiden så att det stämmer överens med servern, går ej att skicka in ett random token)

Utloggning också fixat.
